import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';
import { generateBlinnPhongMaps } from './blinnphong.js';
import { groupIntoTextureSets, scanTextures } from './parse.js';

const dir = path.resolve('test-fixtures/blinn-test');
fs.rmSync(dir, { recursive: true, force: true });
fs.mkdirSync(dir, { recursive: true });

const w = 32;
const h = 32;

await sharp({
  create: { width: w, height: h, channels: 3, background: { r: 200, g: 100, b: 50 } },
})
  .png()
  .toFile(path.join(dir, 'T_mesh_mat_BaseColor-32x32.png'));

await sharp({
  create: { width: w, height: h, channels: 3, background: { r: 128, g: 128, b: 128 } },
})
  .png()
  .toFile(path.join(dir, 'T_mesh_mat_AO-32x32.png'));

await sharp({
  create: { width: w, height: h, channels: 3, background: { r: 128, g: 128, b: 255 } },
})
  .png()
  .toFile(path.join(dir, 'T_mesh_mat_Normal-32x32.png'));

await sharp({
  create: { width: w, height: h, channels: 3, background: { r: 255, g: 128, b: 0 } },
})
  .png()
  .toFile(path.join(dir, 'T_mesh_mat_ORM-32x32.png'));

// Instamat Specular/glossiness — should be archived later, not generated by us
await sharp({
  create: { width: w, height: h, channels: 3, background: { r: 200, g: 200, b: 200 } },
})
  .png()
  .toFile(path.join(dir, 'T_mesh_mat_Specular-32x32.png'));

const set = groupIntoTextureSets(scanTextures(dir, 'mesh'))[0];
assert(set.materials.get('mat')?.Specular, 'Specular detected as input');

const result = await generateBlinnPhongMaps(set, dir);
if (result.generated.length !== 1) {
  throw new Error(`expected 1 Diffuse, got ${result.generated.length}`);
}
if (result.generated.some((p) => p.includes('Specular'))) {
  throw new Error('should not generate Specular');
}

const diffPath = path.join(dir, 'T_mesh_mat_Diffuse-32x32.png');
const { data: diff } = await sharp(diffPath).ensureAlpha().raw().toBuffer({
  resolveWithObject: true,
});
if (Math.abs(diff[0]! - 100) > 1) {
  throw new Error(`Diffuse R expected ~100, got ${diff[0]}`);
}

console.log('Blinn-Phong bake tests passed (Diffuse only).');

function assert(cond: unknown, msg: string): asserts cond {
  if (!cond) throw new Error(msg);
}
